---
title: "timing_comp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
```

### base model one
```{r}
Nospatial_model <- "model{
for(i in 1:n){
Z[i] ~ dnorm(mu[i], inv_var)
 mu[i] <- (beta0+x1[i]*lambda1+x2[i]*lambda2+lambda3*x3[i])+(beta1+x1[i]*theta1+x2[i]*theta2+theta3*x3[i])*log_W[i]

}
beta0~dnorm(0,0.0001)

beta1~dnorm(0,0.0001)

lambda1~dnorm(0,0.0001)

lambda2~dnorm(0,0.0001)

lambda3~dnorm(0,0.0001)

theta2~dnorm(0,0.0001)

theta1~dnorm(0,0.0001)

theta3~dnorm(0,0.0001)

inv_var ~ dgamma(0.01, 0.01)

}

"

```

```{r}
popden <- read.csv("D:/re-emergent RSV timing/population-density-2021.csv",header = T)
popden <- popden[-c(1,9,11),]
popden$Population.Density.2020.Census <- as.numeric(scale(as.numeric(popden$Population.Density.2020.Census)))
popden$familysize <- as.numeric(scale(popden$familysize))
  
data <- list(n=47,Z=y,log_W=log_w,x1=popden$Population.Density.2020.Census,x2=popden$familysize,x3=InD[,'Index'])

censor <- jags.model(textConnection(Nospatial_model),data=data,n.chains = 2)

update(censor,10000)

censorsample <- coda.samples(censor,c("beta0","beta1","lambda1","lambda2","theta1","theta2","lambda3","theta3","inv_var","mu"),100000,thin=20)
```


### right censor survival analysis
```{r}
censormodel <- "model{
for(i in 1:n){
is.censor[i] ~ dinterval(Z[i],t.cen)
Z[i] ~ dlnorm(mu[i], inv_var)
 mu[i] <- (beta0+x1[i]*b01+x2[i]*b02)+(beta1+x1[i]*b11+x2[i]*b12)*log_W[i]

}
beta0~dnorm(0,0.001)

beta1~dnorm(0,0.001)

b01~dnorm(0,0.001)

b11~dnorm(0,0.001)

b02~dnorm(0,0.001)

b12~dnorm(0,0.001)

inv_var ~ dgamma(0.01, 0.01)

}

"

```

## add spatial random effects
```{r}
censor_spatial_model <- "model{
for(i in 1:n){
is.censor[i] ~ dinterval(Z[i],t.cen)
Z[i] ~ dlnorm(mu[i], inv_var)
 mu[i] <- beta0[i] + beta1*log_W[i]
} 

beta0[1:n] ~ dmnorm(intercepts, Leroux)
 
 for(i in 1:n){
 intercepts[i] <- b0+x1[i]*b1+x2[i]*b2}

beta1~dnorm(0,0.0001)

b0~dnorm(0,0.0001)

b1~dnorm(0,0.0001)

b2~dnorm(0,0.0001)

Leroux <- inv.tau*(rho*w.mat + (1 - rho)*Id.mat) # calculate spatial correlated random effects
  inv.tau ~ dgamma(0.01, 0.01) # note the w.mat here is equal to diag(rowSums(neighbors_mat)) - neighbors_mat
  rho~ dunif(0,1)

inv_var ~ dgamma(0.01, 0.01)

}

"
```

```{r}
w.mat=diag(rowSums(neighbors_mat)) - neighbors_mat
data <- list(n=47,Z=exp(z),t.cen=exp(censoring_time),is.censor=censored,log_W=x[,4],x1=x[,2],x2=x[,3],Id.mat=diag(47),w.mat=w.mat)

censor <- jags.model(textConnection(censor_spatial_model),data=data,n.chains = 2)

update(censor,50000)

 
```


### priors on log_w
```{r}
censormodel_var <- "model{
for(i in 1:n){
is.censor[i] ~ dinterval(Z[i],t.cen[i])
Z[i] ~ dlnorm(mu[i], inv_var)
 mu[i] <- (beta0+x1[i]*b01+x2[i]*b02)+(beta1+x1[i]*b11+x2[i]*b12)*log_W[i]
 
 log_W[i]~ dnorm(mean_lnW[i],inv_var_w[i])

}
beta0~dnorm(0,0.001)

beta1~dnorm(0,0.001)

b01~dnorm(0,0.001)

b11~dnorm(0,0.001)

b02~dnorm(0,0.001)

b12~dnorm(0,0.001)

inv_var ~ dgamma(0.01, 0.01)

}

"

```

```{r}
popden <- read.csv("D:/re-emergent RSV timing/population-density-2021.csv",header = T)
onset.2020.FL <- onset.2020$grey-onset.2020$grey[onset.2020$state=='FL']
Z <- onset.2020.FL[-c(which(states=="HI"),which(states=="AK"),which(states=="FL"))]
t.cen <- max(onset.2020$onset)-onset.2020$onset[onset.2020$state=='FL']
n <- length(Z)
t.cen <- rep(t.cen,n)

x1 <- as.numeric(popden$Population.Density.2020.Census)
x1[30] <- 1263
x1[39] <- 1061.4
x1 <- scale(x1)
x2 <- as.numeric(popden$familysize)
x2 <- scale(x2)
is.censor <- ifelse(is.na(Z),1,0)

data.FL <- list(n=n,Z=Z+0.01,t.cen=t.cen,is.censor=is.censor,W=onset.whole.FL+0.01,x1=as.numeric(x1),x2=as.numeric(x2),mean_lnW=lnW_FL_mean,inv_var_w=rep(1000,50))

data <- list(n=47,Z=Z,t.cen=censoring_time,is.censor=censored,log_W=lnW_FL_mean,x1=x_1,x2=x_2)
tinits1 <- 1+onset.2020$onset
is.na(tinits1) <- complete.cases(onset.2020$grey)
tinits2 <- tinits1+1
censorinit <- list(list(Z=tinits1),list(Z=tinits2))
```

```{r}
censor <- jags.model(textConnection(censormodel),data=data,n.chains = 2)

update(censor,100000)

censorsample <- coda.samples(censor,c("beta0","beta1","b01","b02","b11","b12"),500000,thin=10)
```

```{r}
#par(ask=T)
traceplot(censorsample)
summary(censorsample)
densplot(censorsample)
```

```{r}
censor <- jags.model(textConnection(censormodel),data=data.FL,n.chains = 2)

update(censor,10000)

censorsample <- coda.samples(censor,c("beta0","beta1","b01","b02","b11","b12","log_W"),50000,thin=10)
```

```{r}
#par(ask=T)
traceplot(censorsample)
summary(censorsample)
densplot(censorsample)
```

```{r}
post <- as.data.frame(as.matrix(censorsample))
b12 <- post[,"b12"]
beta1 <- post[,"beta1"]
plot(b12*x2[1]+beta1,type="l")
plot(b12*x2[2]+beta1,type="l")
```

### right censor sensitivity analysis
```{r}
censormodel_sim <- "model{
for(i in 1:n){
is.censor[i] ~ dinterval(Z[i],t.cen[i])
Z[i] ~ dlnorm(mu[i], inv_var)
 mu[i] <- (beta0)+(beta1)*log(W[i])

}
beta0~dnorm(0,0.001)

beta1~dnorm(0,0.001)

inv_var ~ dgamma(0.01, 0.01)

}

"

```

```{r}
y <- onset.2020$onset-onset.2020$onset[onset.2020$state=='FL']
z <- c()
z[censored == 0]<-y[censored == 0]
z[censored == 1]<-NA
y <- y[-c(which(states=="HI"),which(states=="AK"),which(states=="FL"))]
x_1 <- as.numeric(x1)[-c(which(states=="HI"),which(states=="AK"),which(states=="FL"))]
x_2 <- as.numeric(x2)[-c(which(states=="HI"),which(states=="AK"),which(states=="FL"))]

x <- matrix(c(rep(1,length(y)),x_1,x_2,lnW_FL_mean,lnW_FL_mean*x_1,lnW_FL_mean*x_2),nrow=length(y),ncol = 6)

m <- matrix(0,nrow=length(y),ncol = 2*length(y))
for(i in 1:length(y)){
        m[i,(1+(i-1)*2):(2*i)] <- c(1,log_w[i])
}

saveRDS(y,"D:/re-emergent RSV timing/sample_requiredata/y.rds")
saveRDS(x,"D:/re-emergent RSV timing/sample_requiredata/x.rds")
saveRDS(m,"D:/re-emergent RSV timing/sample_requiredata/m.rds")
saveRDS(neighbors_mat,"D:/re-emergent RSV timing/sample_requiredata/neighbors_mat.rds")
saveRDS(censored,"D:/re-emergent RSV timing/sample_requiredata/censored.rds")
saveRDS(censoring_time,"D:/re-emergent RSV timing/sample_requiredata/censoring_time.rds")
```

```{r}
library(rstan)

fit = stan(model_code=bern.stan, data=list(y=y, N=N), iter=5000)
```

